name: Tests and linter

on:
  push:
    branches:
      - '**'

jobs:
  run-linters:
    name: Run linter and tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - run: yarn install
      - run: yarn lint
      - run: yarn test
